### ISSUE TITLE
Main 페이지 이미지 관련

### ISSUE THREAD

**Issue by swings134man** [swings134man/tradingDay#1]
## 논의 사항 
>  React Main Page IMAGE 수정(교체)에 대한 의견.

### 상세
1. 소개 Background Image
2. 하단 웹 사이트 소개 이미지 3건 
-> Trade 
-> 제안서
-> QnA

### 제안 사항 - (택1) 추가 가능
1. 기능 동작 화면 캡쳐 후 사용
2. 기능 관련 무료 Icon 사용 
3. 상관없는 예쁜 Icon 사용

**Comment by caporatang** [comment]
기능동작 화면 캡처 후 사용이 무슨 뜻인지는 모르겠으나,  상관없는 아이콘 쓰는게 나을듯.
