### ISSUE TITLE
2. Security Permit ALL (swagger) 관련

### ISSUE THREAD

**Issue by swings134man** [swings134man/tradingDay#2]
### JWTSecurity Config 파일 수정에 관한 건
> swagger url 경로 관련

#### 문제점
1. ignoring() 으로 설정 시 -> 불필요한 log 발생 

### 현재 수정 내역
1. 전역 security configure() 내부에서 antMatchers 로 등록 후 해결 가능 
2. 기존 webConfigure  = 주석 처리 .
#### Side Effect 
1. React 충돌 여부 확인
2. Swagger UI 접속 불가 & API Test 진행 불가한지 확인.

**Comment by caporatang** [comment]
확인완료
