### ISSUE TITLE
3. Login Error 

### ISSUE THREAD

**Issue by swings134man** [swings134man/tradingDay#3]
### Login Error 
> 로그인 에러 문제 

#### 테스트 케이스 및 상황
1. DB 상 계정 정보 존재. 
2. Server, React 기동. 
3. 자체 API 로그인시  -> "아이디와 비밀번호를 확인하세요" 메시지 

#### Server message
>  JWTLoginFilter.jva 69 Line 에러
> NPE 발생.

**Comment by caporatang** [comment]
쿠키 지우고 시도해보세요~

**Comment by swings134man** [comment]
ToKen ForEach fix
