### ISSUE TITLE
4. Jar 파일 실행 (React Error)

### ISSUE THREAD

**Issue by swings134man** [swings134man/tradingDay#4]
## 배포 에러 
> Gradle Build -> Jar 파일 빌드 후 기동시 (java -jar 스냅샷.jar)

###  AS-IS 
> 빌드 후 jar 실행 -> localhost 3000 or 8000 접근 가능. 

#### 문제상황
> jar 빌드 후 기동시 3000 포트 접근 불가.
> 8080(서버 포트) 접근시 OAuth2.0 Page 로딩되며 모든 접근권한 X

**Comment by swings134man** [comment]
Solution 1. 

build.gradle 내부에 
1.추가 
task runReactServer(type: NpmTask) { 
       workingDir = file("reactFront"); //리액트 경로
       args = ["start"] 
}

2. 추가
bootRun.doFirst{
  runReactServer
}

이후 jar 파일 빌드 후 실행 -> localhost:3000 포트로 접근.

해당 Task(이슈)는 추후 진행상황 공유 하겠음.

**Comment by caporatang** [comment]
로그인 하지 않고 8080포트 접근시 Oauth2.0(kakao, google) 페이지가 출력되는것은 정상입니다.
Security Config에 formLogin 선언없이 oauth2Login을 선언해놓아서, 디폴트로 Oauth2.0이 로그인페이지가 되는것입니다.
